parameters:

    #
    # Event Listeners
    #
    mmoreram.controllerextra.event_listeners.form_annotation_event_listener.class: Mmoreram\ControllerExtraBundle\EventListener\FormAnnotationEventListener
    mmoreram.controllerextra.event_listeners.flush_annotation_event_listener.class: Mmoreram\ControllerExtraBundle\EventListener\FlushAnnotationEventListener
    mmoreram.controllerextra.event_listeners.paginator_annotation_event_listener.class: Mmoreram\ControllerExtraBundle\EventListener\PaginatorAnnotationEventListener