parameters:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolvers.entity_annotation_resolver.class: Mmoreram\ControllerExtraBundle\Resolver\EntityAnnotationResolver

services:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolvers.entity_annotation_resolver:
        class: %mmoreram.controllerextra.resolvers.entity_annotation_resolver.class%
        arguments:
            doctrine: @doctrine
            bundles: @=service("kernel").getBundles()
            default_name: %mmoreram.controllerextra.form_default_name%
            default_manager: %mmoreram.controllerextra.entity_default_manager%
            default_persist: %mmoreram.controllerextra.entity_default_persist%
        tags:
            - { name: controller_extra.annotation }
