parameters:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolvers.paginator_annotation_resolver.class: Mmoreram\ControllerExtraBundle\Resolver\PaginatorAnnotationResolver

services:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolvers.paginator_annotation_resolver:
        class: %mmoreram.controllerextra.resolvers.paginator_annotation_resolver.class%
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            knp_paginator: "@knp_paginator"
        calls:
            - [setDefaultNumber, [%mmoreram.controllerextra.paginator_number_default%]]
            - [setDefaultPage, [%mmoreram.controllerextra.paginator_page_default%]]
            - [setDefaultOrderByField, [%mmoreram.controllerextra.paginator_orderby_field_default%]]
            - [setDefaultOrderByMode, [%mmoreram.controllerextra.paginator_orderby_mode_default%]]
        tags:
            - { name: controller_extra.annotation }