parameters:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolvers.entity_annotation_resolver.class: Mmoreram\ControllerExtraBundle\Resolver\EntityAnnotationResolver

services:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolvers.entity_annotation_resolver:
        class: %mmoreram.controllerextra.resolvers.entity_annotation_resolver.class%
        arguments:
            bundles: @=service("kernel").getBundles()
            default_name: %mmoreram.controllerextra.form_default_name%
        tags:
            - { name: controller_extra.annotation }
