parameters:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolvers.log_annotation_resolver.class: Mmoreram\ControllerExtraBundle\Resolver\LogAnnotationResolver

services:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolvers.log_annotation_resolver:
        class: %mmoreram.controllerextra.resolvers.log_annotation_resolver.class%
        arguments:
            form_registry: @form.registry
            form_factory: @form.factory
        calls:
            - [setDefaultHandler, [%mmoreram.controllerextra.handler_default_handler%]]
        tags:
            - { name: controller_extra.annotation }