parameters:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolver.entity_annotation_resolver.class: Mmoreram\ControllerExtraBundle\Resolver\EntityAnnotationResolver

services:

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolver.entity_annotation_resolver:
        class: %mmoreram.controllerextra.resolver.entity_annotation_resolver.class%
        arguments:
            doctrine: @doctrine
            entity_provider: @mmoreram.controllerextra.provider.entity_provider
            default_name: %mmoreram.controllerextra.form_default_name%
            default_manager: %mmoreram.controllerextra.entity_default_manager%
            default_persist: %mmoreram.controllerextra.entity_default_persist%
        tags:
            - { name: controller_extra.annotation }
