services:

    #
    # Event Listeners
    #
    mmoreram.controllerextra.event_listeners.resolver_event_listener:
        class: %mmoreram.controllerextra.event_listeners.resolver_event_listener.class%
        arguments:
            kernel: @kernel
            annotations_reader: @annotation_reader
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    #
    # Resolvers
    #
    mmoreram.controllerextra.resolvers.form_annotation_resolver:
        class: %mmoreram.controllerextra.resolvers.form_annotation_resolver.class%
        arguments:
            form_registry: @form.registry
            form_factory: @form.factory
        calls:
            - [setActive, [%mmoreram.controllerextra.form_active%]]
        tags:
            - { name: controller_extra.annotation }

    mmoreram.controllerextra.resolvers.flush_annotation_resolver:
        class: %mmoreram.controllerextra.resolvers.flush_annotation_resolver.class%
        arguments:
            doctrine: @doctrine
        calls:
            - [setActive, [%mmoreram.controllerextra.flush_active%]]
            - [setDefaultManager, [%mmoreram.controllerextra.flush_default_manager%]]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
            - { name: controller_extra.annotation }

    mmoreram.controllerextra.resolvers.paginator_annotation_resolver:
        class: %mmoreram.controllerextra.resolvers.paginator_annotation_resolver.class%
        arguments:
            entity_manager: @doctrine.orm.entity_manager
            knp_paginator: "@?knp_paginator"
        calls:
            - [setActive, [%mmoreram.controllerextra.paginator_active%]]
            - [setDefaultNumber, [%mmoreram.controllerextra.paginator_number_default%]]
            - [setDefaultPage, [%mmoreram.controllerextra.paginator_page_default%]]
            - [setDefaultOrderByField, [%mmoreram.controllerextra.paginator_orderby_field_default%]]
            - [setDefaultOrderByMode, [%mmoreram.controllerextra.paginator_orderby_mode_default%]]
        tags:
            - { name: controller_extra.annotation }