language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

install: composer install --prefer-source --no-interaction

script: phpunit -c phpunit.xml --coverage-text

notifications:
    email: false