language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm-nightly

env:
    - SYMFONY_VERSION="~2.3"

before_install:
    - composer require --no-update symfony/monolog-bundle:~2.3
    - composer require --no-update symfony/form:~2.3
    - composer require --no-update doctrine/orm:~2.3
    - composer require --no-update white-october/pagerfanta-bundle:~1.0

install:
    - composer install --prefer-source --no-interaction

script:
    - phpunit -c phpunit.xml.dist

notifications:
    email: false